package ap.trainingdiary.type;
public enum NodeType{
	TRAININGNODEUSEROBJECT,
	DAYNODEUSEROBJECT,
	MONTHNODEUSEROBJECT,
	YEARNODEUSEROBJECT,
	TRAININGSNODEUSEROBJECT,
	ROOTNODEUSEROBJECT,
	TEMPLATENODEUSEROBJECT,
	TEMPLATESNODEUSEROBJECT,
	COMMENTNODEUSEROBJECT,
	COMMENTSNODEUSEROBJECT
}
